services:
  - type: web
    name: langgraph-hf-chatbot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run U_bot_frontend.py --server.port=10000 --server.address=0.0.0.0"
    envVars:
      - key: HUGGINGFACEHUB_API_TOKEN
        sync: false
